Repository slackhq/nebula, pull requests merged in 2021-12, with the labels that each got.

#595 overlay: fix tun.RouteFor getting *net.IP
  overlay/route.go
  overlay/route_test.go
  overlay/tun_wintun_windows.go
Labels: bug, needs-changelog

#602 fix crash with `-test`
  main.go
Labels: bug

#603 update golang.org/x/crypto
  go.mod
  go.sum
Labels: needs-changelog

#590 don't set ConnectionState to nil
  hostmap.go
  outside.go
Labels: bug, needs-changelog

#599 Allow setup of a CA pool from bytes that contain expired certs
  cert.go
  cert/ca.go
  cert/cert_test.go
  cert/errors.go
Labels: needs-changelog
