Repository slackhq/nebula, pull requests merged in 2023-03, with the labels that each got.

#738 firewall: add option to send REJECT replies
  .github/workflows/smoke/Dockerfile
  .github/workflows/smoke/genconfig.sh
  .github/workflows/smoke/smoke.sh
  examples/config.yml
  firewall.go
  inside.go
  iputil/packet.go
  outside.go
  overlay/tun_disabled.go
Labels: needs-changelog, slack

#759 add calculated_remotes
  calculated_remote.go
  calculated_remote_test.go
  examples/config.yml
  handshake_manager.go
  handshake_manager_test.go
  hostmap.go
  inside.go
  lighthouse.go
  udp/udp_all.go
Labels: enhancement, needs-changelog, slack

#737 ssh: add save-mutex-profile
  ssh.go
Labels: needs-defined-net-review

#721 add punchy.respond_delay config option
  examples/config.yml
  lighthouse.go
  punchy.go
  punchy_test.go
Labels: needs-defined-net-review

#408 remove probes of the lighthouse(s)
  connection_manager.go
Labels: needs-defined-net-review

#833 Use atomic.Pointer for certState
  connection_manager_test.go
  connection_state.go
  control_tester.go
  interface.go
  ssh.go
Labels: needs-slack-review
