Repository slackhq/nebula, pull requests merged in 2023-05, with the labels that each got.

#856 add boringcrypto Makefile targets
  Makefile
  boring.go
  interface.go
  notboring.go
  stats.go
Labels: slack

#838 Rehandshaking
  connection_manager.go
  connection_manager_test.go
  control_tester.go
  e2e/handshakes_test.go
  e2e/helpers_test.go
  e2e/router/router.go
  handshake_manager.go
  handshake_manager_test.go
  hostmap.go
  inside.go
  interface.go
  lighthouse_test.go
  outside.go
  punchy.go
  relay_manager.go
Labels: needs-defined-net-review, cla:signed

#857 Clear lighthouse cache for a vpn ip on a dead connection when its the final hostinfo
  connection_manager.go
Labels: cla:signed

#858 Always disconnect block listed hosts
  cert/cert.go
  cert/cert_test.go
  cert/errors.go
  connection_manager.go
Labels: cla:signed

#769 Support NIST curve P256
  .github/workflows/smoke.yml
  .github/workflows/smoke/build.sh
  .github/workflows/smoke/smoke.sh
  Makefile
  cert.go
  cert/cert.go
  cert/cert.pb.go
  cert/cert.proto
  cert/cert_test.go
  cmd/nebula-cert/ca.go
  cmd/nebula-cert/ca_test.go
  cmd/nebula-cert/keygen.go
  cmd/nebula-cert/keygen_test.go
  cmd/nebula-cert/print_test.go
  cmd/nebula-cert/sign.go
  cmd/nebula-cert/sign_test.go
  cmd/nebula-cert/verify_test.go
  connection_manager_test.go
  connection_state.go
  e2e/helpers_test.go
  noiseutil/nist.go
Labels: slack, needs-defined-net-review, needs-slack-review

#860 Fix test on master
  cert/cert_test.go
Labels: cla:signed

#851 Have lighthouses ack updates to reduce test packet traffic
  cert/cert.pb.go
  connection_manager.go
  lighthouse.go
  message_metrics.go
  nebula.pb.go
  nebula.proto
Labels: cla:signed

#863 Try rehandshaking a main hostinfo after releasing hostmap read lock
  connection_manager.go
Labels: cla:signed

#865 document P256 and BoringCrypto
  README.md
Labels: documentation

#864 add SECURITY.md
  .github/ISSUE_TEMPLATE/config.yml
  SECURITY.md
Labels: documentation

#839 Add ability to respect the system route table for unsafe route on linux
  cidr/tree4.go
  cidr/tree4_test.go
  examples/config.yml
  overlay/tun.go
  overlay/tun_android.go
  overlay/tun_darwin.go
  overlay/tun_freebsd.go
  overlay/tun_ios.go
  overlay/tun_linux.go
  overlay/tun_linux_test.go
  overlay/tun_tester.go
  overlay/tun_windows.go
Labels: cla:signed

#507 Add destination CIDR checking
  examples/config.yml
  firewall.go
  firewall_test.go
Labels: cla:signed

#867 issue templates: remove Report Security Vulnerability
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#868 Fix go vet
  firewall_test.go
Labels: cla:signed

#877 When interpreting DNS lookup results, create the IPv4 address with ne…
  remote_list.go
Labels: cla:signed

#878 Prepare 1.7.1 release
  CHANGELOG.md
Labels: cla:signed

#886 Fix reconfig freeze attempting to send to an unbuffered, unread channel
  lighthouse.go
  lighthouse_test.go
  remote_list.go
Labels: cla:signed
