Repository slackhq/nebula, pull requests merged in 2023-07, with the labels that each got.

#919 Update README to include a link to go install docs
  README.md
Labels: documentation, cla:signed

#929 Attempt to notify systemd of service readiness on linux
  cmd/nebula/main.go
  cmd/nebula/notify_linux.go
  cmd/nebula/notify_notlinux.go
  dist/arch/nebula.service
  dist/fedora/nebula.service
  examples/service_scripts/nebula.service
Labels: cla:signed

#843 Pull hostmap and pending hostmap apart, remove unused functions
  connection_manager_test.go
  control.go
  control_test.go
  control_tester.go
  dns_server.go
  handshake.go
  handshake_ix.go
  handshake_manager.go
  handshake_manager_test.go
  hostmap.go
  hostmap_test.go
  inside.go
  main.go
  outside.go
  relay_manager.go
  ssh.go
Labels: needs-slack-review, cla:signed

#934 Guard e2e tun and udp channels on close
  e2e/handshakes_test.go
  overlay/tun_tester.go
  udp/udp_tester.go
Labels: cla:signed

#916 Add support for NetBSD
  Makefile
  examples/config.yml
  overlay/tun_netbsd.go
  udp/udp_netbsd.go
Labels: NeedsDecision, cla:signed

#935 Send the lh update worker into its own routine instead of taking over the reload routine
  control.go
  lighthouse.go
  lighthouse_test.go
  main.go
Labels: cla:signed

#938 Remove unused config code (last edited 4yrs ago)
  main.go
Labels: cla:signed
