Repository slackhq/nebula, pull requests merged in 2023-11, with the labels that each got.

#955 Clean up a hostinfo to reduce memory usage
  connection_state.go
  control.go
  control_test.go
  handshake.go
  handshake_ix.go
  handshake_manager.go
  handshake_manager_test.go
  hostmap.go
  inside.go
  outside.go
Labels: cla:signed

#1004 Use generics for CIDRTrees to avoid casting issues
  allow_list.go
  allow_list_test.go
  calculated_remote.go
  cidr/tree4.go
  cidr/tree4_test.go
  cidr/tree6.go
  cidr/tree6_test.go
  firewall.go
  firewall_test.go
  hostmap.go
  lighthouse.go
  overlay/route.go
  overlay/route_test.go
  overlay/tun_darwin.go
  overlay/tun_freebsd.go
  overlay/tun_linux.go
  overlay/tun_netbsd.go
  overlay/tun_openbsd.go
  overlay/tun_tester.go
  overlay/tun_water_windows.go
  overlay/tun_wintun_windows.go
Labels: cla:signed

#859 Default `pki.disconnect_invalid` to true and make it reloadable
  connection_manager.go
  connection_manager_test.go
  examples/config.yml
  interface.go
  main.go
Labels: cla:signed

#957 firewall reject packets: cleanup error cases
  inside.go
  iputil/packet.go
  iputil/packet_test.go
  outside.go
Labels: bug

#965 add gvisor based service library
  control.go
  e2e/handshakes_test.go
  e2e/helpers.go
  e2e/helpers_test.go
  examples/go_service/main.go
  go.mod
  go.sum
  main.go
  overlay/tun.go
  overlay/user.go
  service/listener.go
  service/service.go
  service/service_test.go
Labels: NeedsDecision, cla:signed

#1010 Added firewall.rules.hash metric
  firewall.go
  interface.go
  main.go
Labels: cla:signed
