Repository slackhq/nebula, pull requests merged in 2024-04, with the labels that each got.

#1043 Support reloading `preferred_ranges`
  connection_manager.go
  connection_manager_test.go
  control.go
  control_test.go
  handshake_ix.go
  handshake_manager.go
  handshake_manager_test.go
  hostmap.go
  hostmap_test.go
  main.go
  ssh.go
Labels: cla:signed

#1114 Remove tcp rtt tracking from the firewall
  firewall.go
  firewall_test.go
  inside.go
  outside.go
Labels: cla:signed

#1115 Allow `::` in lighthouse.dns.host config
  dns_server.go
  dns_server_test.go
Labels: cla:signed

#1128 Remove Fedora nebula.service file
  dist/fedora/nebula.service
Labels: cla:signed

#1109 Add suggested filenames for collected profiles in the ssh commands
  ssh.go
Labels: cla:signed

#1116 Don't log invalid certificates
  LOGGING.md
  examples/config.yml
  handshake_ix.go
Labels: cla:signed

#981 update to go1.22
  .github/workflows/gofmt.yml
  .github/workflows/release.yml
  .github/workflows/smoke.yml
  .github/workflows/smoke/smoke-relay.sh
  .github/workflows/smoke/smoke.sh
  .github/workflows/test.yml
  Makefile
  go.mod
  go.sum
  service/service.go
Labels: cla:signed

#763 add ssh command to print device info
  ssh.go
Labels: cla:signed

#1132 Remove Arch nebula.service file
  dist/arch/nebula.service
Labels: cla:signed

#1129 Remove Vagrant example
  examples/quickstart-vagrant/README.md
  examples/quickstart-vagrant/Vagrantfile
  examples/quickstart-vagrant/ansible/ansible.cfg
  examples/quickstart-vagrant/ansible/filter_plugins/to_nebula_ip.py
  examples/quickstart-vagrant/ansible/inventory
  examples/quickstart-vagrant/ansible/playbook.yml
  examples/quickstart-vagrant/ansible/roles/nebula/defaults/main.yml
  examples/quickstart-vagrant/ansible/roles/nebula/files/systemd.nebula.service
  examples/quickstart-vagrant/ansible/roles/nebula/files/vagrant-test-ca.crt
  examples/quickstart-vagrant/ansible/roles/nebula/files/vagrant-test-ca.key
  examples/quickstart-vagrant/ansible/roles/nebula/handlers/main.yml
  examples/quickstart-vagrant/ansible/roles/nebula/tasks/main.yml
  examples/quickstart-vagrant/ansible/roles/nebula/templates/config.yml.j2
  examples/quickstart-vagrant/ansible/roles/nebula/vars/main.yml
  examples/quickstart-vagrant/requirements.yml
Labels: cla:signed

#1111 chore: fix function name in comment
  cert/cert.go
Labels: cla:signed

#1003 Add support for LoongArch64
  Makefile
  udp/udp_linux_64.go
Labels: WaitingForInfo, cla:signed

#1067 Add Vagrant based smoke tests
  .github/workflows/smoke-extra.yml
  .github/workflows/smoke/build.sh
  .github/workflows/smoke/genconfig.sh
  .github/workflows/smoke/smoke-vagrant.sh
  .github/workflows/smoke/vagrant-freebsd-amd64/Vagrantfile
  .github/workflows/smoke/vagrant-linux-386/Vagrantfile
  .github/workflows/smoke/vagrant-linux-amd64-ipv6disable/Vagrantfile
  .github/workflows/smoke/vagrant-netbsd-amd64/Vagrantfile
  .github/workflows/smoke/vagrant-openbsd-amd64/Vagrantfile
  Makefile
Labels: smoke-test-extra
